services:
  api:
    build: .
    env_file: ./.env
    ports:
      - "${PORT}:${PORT}"
    environment:
      - MONGODB_URL=${MONGODB_URL}
      - PORT=${PORT}
      - PRIVATE_KEY=${PRIVATE_KEY}
      - RPC_URL=${RPC_URL}
      - PINATA_API_KEY=${PINATA_API_KEY}
      - PINATA_API_SECRET=${PINATA_API_SECRET}
      - PINATA_API_URL=${PINATA_API_URL}
      - PINATA_GATEWAY=${PINATA_GATEWAY}
      - RABBITMQ_URL=${RABBITMQ_URL}
    depends_on:
      - mongo
      - rabbitmq
    volumes:
      - .:/usr/src/node-app
    networks:
      - node-network
    command: npm run start:api

  worker:
    build: .
    env_file: ./.env
    command: npm run start:worker
    depends_on:
      - mongo
      - rabbitmq
    volumes:
      - .:/usr/src/node-app
    networks:
      - node-network

  cron:
    build: .
    env_file: ./.env
    command: npm run start:cron
    depends_on:
      - mongo
      - rabbitmq
    volumes:
      - .:/usr/src/node-app
    networks:
      - node-network

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    command: --replSet rs0
    networks:
      - node-network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - node-network

networks:
  node-network:
